export const ADD_FAVORITE_COMPANY = "ADD_FAVORITE_COMPANY";
export const DELETE_FAVORITE_COMPANY = "DELETE_FAVORITE_COMPANY";
export const CHANGE_FAVORITE_STATUS = "CHANGE_FAVORITE_STATUS";
export const SEARCHED_RESULT = "SEARCHED_RESULT";
